# UI
APP_WIDTH = 1280
APP_HEIGHT = 720

MODE_BUTTON_WIDTH = 180
MODE_BUTTON_HEIGHT = 60

FONT = "redditsans_regular.ttf"
# Ambilight

HORIZONTAL_ZONES = 30
VERTICAL_ZONES = 16
SLICED_PIXELS = 40

FRAME_START = 255
NUM_LEDS = HORIZONTAL_ZONES*2 + VERTICAL_ZONES*2
FPS = 60

BRIGHTNESS = 15

from enum import IntEnum
class Mode(IntEnum):
    AMBILIGHT = 0
    STATIC = 1

# SERIAL COMM
SERIAL_PORT = 'COM3' 
BAUD_RATE = 115200